### ISSUE TITLE
app:keepCountingDownInBackground设置为true后导致多个按钮倒计时错误

### ISSUE THREAD

**Issue by Saxxhw** [mlxy/CountdownButton#8]
您好，在使用过程中发现了一个小问题，因为需求导致项目中有多处需要使用该控件，设置app:keepCountingDownInBackground为true后，发现第一个按钮的倒计时成功，跳转第二个界面之后，该界面中的CountdownButton的倒计时是与前一个Button相同的，原因是该控件在整个应用只保存了一个数值在Sp里，项目里的全部CountdownButton按钮都回去设置app:keepCountingDownInBackground为true后都回去读取这个值改变当前倒计时。希望大神可以继续优化一下

**Comment by chihane** [comment]
感谢关注。
SharedPreferences 其实不是个好解决方案，我琢磨一下改进方法。

**Comment by chihane** [comment]
试着加了个标识符用以区分不同的按钮
check this out -> cf7c01cab3f9297a90de129a60c7401133b10bc1

1.6版本已经上传 MavenCentral，文档也已经更新，可以试一下

**Comment by Saxxhw** [comment]
好滴好滴~大神效率好高啊

**Comment by Saxxhw** [comment]
不过要实现keepCountingDownInBackground这个需求，把剩余时间和按钮标识存储起来是一定要的，除了SharedPreferences之外，无外乎就数据库、静态对象、文件存储之类的了，我倒是觉得用SharedPreferences存储已经是很好的解决方案了。
